let Globals = {
    'APP_NAME'              : 'TRAINING',
    'API_KEY'               : process.env.API_KEY,
    'LOGO'                  : 'api/images/app_icon.png',
    'ARROW_IMAGE'           : 'api/images/arrow-right.gif',
    'BASE_URL'              : process.env.BASE_URL,
    'BASE_URL_WITHOUT_API'  : process.env.BASE_URL_WITHOUT_API,
    'PORT_BASE_URL'         : process.env.PORT_BASE_URL,
    'S3_BUCKET_ROOT'        : process.env.S3_BUCKET_ROOT,
    'KEY'                   : process.env.KEY,
    'IV'                    : process.env.IV,
    'EMAIL_ID'              : process.env.EMAIL_ID,
    'EMAIL_PASSWORD'        : process.env.EMAIL_PASSWORD,
    'API_PASSWORD'          : process.env.API_PASSWORD,
    'USER_IMAGE'            : 'user/',
    'PER_PAGE'              : '10',
    'PUSH_KEY'              : '',
    'P8_CERTIFICATE_NAME'   : './pem/AuthKey_A8ZG65FW75.p8',
    'KEY_ID'                : '',
    'TEAM_ID'               : '',
    'CUSTOMER_BUNDLE_ID'    : 'com.training.customer',
}
module.exports = Globals;